### ISSUE TITLE
No git version/release tags since 2.1.1 release

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/recog#125]
It looks like the gem version is at 2.1.5, but the github releases/tags doesn't show anything new since 2.1.1. Something change with the deployment process?

cc @jhart-r7

**Comment by jhart-r7** [comment]
@gschneider-r7 thanks for reporting this!

Despite this being listed clearly in the last step in https://github.com/rapid7/recog/blob/master/CONTRIBUTING.md#releasing-new-versions, I've forgotten to do it from time to time.  I've since pushed all of the missing tags.

In the future we can find a better way to build and release this gem that works for all uses cases.
