### ISSUE TITLE
hw.device vs os.device

### ISSUE THREAD

**Issue by zt2** [rapid7/recog#147]
Hi

I was confused by two fields: hw.device / os.device

seems like they all hold some device information from host

```xml
<param pos="0" name="hw.device" value="Printer"/>
<param pos="0" name="os.device" value="Printer"/>
```

but what different between them ? which one should I use ?

thx

**Comment by jhart-r7** [comment]
This is partially an artifact from when Recog's content was originally extracted from Nexpose.  It seems like the bulk of the fingerprintints here use `os.device` but some use `hw.device`.  The former seems to be used more frequently.  We should make these consistent since they seem to convey the same information.

**Comment by zt2** [comment]
agree that, thx
